
@startuml P120_register_entity_simple_ko

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 설정
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'=== Header and Footer ===
header OPEN-DID 기술 규격
footer
  	Page %page% of %lastpage% at %date("yyyy-MM-dd hh:mm:ss")
end footer

'=== 제목 ===
title
	<size:25>P120 : Entity 등록</size>
end title

'=== 옵션 ===
autonumber "<b>(#)</b>"

'=== Panticipants ===
skinparam ParticipantPadding 20
skinparam BoxPadding 20
skinparam MaxMessageSize 500
skinparam MinClassWidth 80


box Entity 사업자 #AliceBlue
    participant "**Entity**" as ENT <<WAS>> #WhiteSmoke
end box

box TAS 사업자 #AliceBlue
    participant "**TAS**" as TAS <<WAS>> #WhiteSmoke
end box

box 신뢰저장소
    participant "**blockchain**" as BC <<Storage>> #WhiteSmoke
end box 

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 상수
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
!$refdoc = "별도 문서 참조"
!$doc = "데이터명세 문서 참조"


'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 내용
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|||

== Entity DID Document 등록 ==
rnote across #white
    Entity DID Document 등록은 본 규격에서 다루지 않음. 
end note

|||

== P120-1 : Entity 등록 시작 요청 ==
ENT -> TAS++ : Entity 등록 시작 요청
rnote right of ENT #Lavender
    **[M120_REQ : Entity 등록 시작 요청]**
end note

TAS --> ENT--: Entity 등록 시작 응답
rnote right of ENT #Lavender
    **[M120_RES : Entity 등록 시작 응답]**
end note

|||
== P120-2 : ECDH 요청 ==
ENT -> TAS++ : ECDH 요청
rnote right of ENT #Lavender
    **[M120_REQ : ECDH 요청]**
end note

TAS --> ENT--: ECDH 응답
rnote right of ENT #Lavender
    **[M120_RES : ECDH 응답]**
end note

|||
ENT <--> TAS : 상호인증 및 키 교환

|||
== P120-3 : Entity 등록 요청 ==
ENT -> TAS++ : Entity 등록 요청
rnote right of ENT #Lavender
    **[M120_REQ : Entity 등록 요청]**
end note

TAS -> TAS : Entity 가입증명서VC 생성
TAS -> BC : 가입증명서VC 메타데이터 등록

TAS --> ENT--: Entity 등록 응답
rnote right of ENT #Lavender
    **[M120_RES : Entity 등록 응답]**
    body:
        암호화된 Entity 가입증명서
end note

|||
== P120-4 : Entity 등록 완료 ==
ENT -> TAS++ : Entity 등록 완료 요청
rnote right of ENT #Lavender
    **[M120_REQ : Entity 등록 완료 요청]**
end note

TAS --> ENT--: Entity 등록 완료 응답
rnote right of ENT #Lavender
    **[M120_RES : Entity 등록 완료 응답]**
end note

|||
|||
@enduml

