@startuml
participant app as "Client App"
participant tas as "TAS Server"

app ->> tas : PII 등록 요청 (PII)
tas -->> app : 결과 전달 (기등록 여부)

app ->> tas : DIDDoc 등록 요청

note right of tas : File Wallet은 앱이 재설치되면 새로운 월렛을 사용해야 한다.

tas -> tas : 기존 월렛, DIDDoc 폐기
tas -> tas : 정보 갱신 (사용자, 월렛, 앱)


app ->> tas : 확인 요청
tas -->> app : OK
@enduml