@startuml P131_register_wallet

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Settings
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'=== Header and Footer ===
header OPEN-DID Technical Specification
footer
  	Page %page% of %lastpage% at %date("yyyy-MM-dd hh:mm:ss")
end footer

'=== Title ===
title
	<size:25>P131: Wallet Registration</size>
end title

'=== Options ===
autonumber "<b>(#)</b>"

'=== Participants ===
skinparam ParticipantPadding 20
skinparam BoxPadding 20
skinparam MaxMessageSize 500
skinparam MinClassWidth 80

box Mobile #OldLace  
    participant "**Wallet**" as WALLET <<Wallet>> #WhiteSmoke 
    participant "**Certified App**" as CA <<App>> #WhiteSmoke 
end box

box Wallet Provider #AliceBlue
    participant "**Wallet Service**" as WP <<WAS>> #WhiteSmoke
end box

box TAS Provider #AliceBlue
    participant "**TAS**" as TAS <<WAS>> #WhiteSmoke
end box


box Trusted Storage
    participant "**blockchain**" as BC <<Storage>> #WhiteSmoke
end box 

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Constants
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
!$refdoc = "Refer to separate document"
!$doc = "Refer to data specification document"


'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Content
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|||


CA -> WALLET++: Wallet Creation Request

== Request for Allowed CA List ==
WALLET -> TAS++: Request for Allowed CA List
rnote right of WALLET #LightGray        
    **[API_REQ: Request for Allowed CA List]**
    query:
        wallet
end note

return Response for Allowed CA List
rnote right of WALLET #LightGray        
    **[API_RES: Response for Allowed CA List]**
    body:
        count
        items
end note

||| 
== Wallet Creation ==
WALLET -> WALLET: Wallet Initialization

||| 
== Wallet DID Document Creation ==
WALLET -> WALLET: Generate Wallet Key (Device Key)

WALLET -> WALLET: (DidDoc)didDoc \
               \n  = Create DID Document
WALLET -> WALLET: (OwnerDidDoc)ownerDidDoc\
               \n  = Sign individual key (didDoc)

WALLET -> WP++: Request DID Document Signature\n{ownerDidDoc}
    WP -> WP: walletId = Generate Wallet Identifier
    WP -> WP: (AttestedDidDoc)attDidDoc = {\
        \n   walletId,\
        \n   ownerDidDoc,\
        \n   provider = Wallet Provider Information,\
        \n   nonce = Generate nonce\
        \n }
    WP -> WP: Wallet Provider Signature\
        \n* signAssert(attDidDoc)
    WP -> WP: Save Mapping Information to DB\
        \n* walletId (Wallet Identifier)\
        \n* walletDid (Wallet DID)
return {attDidDoc}

||| 
== P131: Wallet Registration Request ==
WALLET -> TAS++: Wallet Registration Request
rnote right of WALLET #LightGray        
    **[M131_REQ: Wallet Registration Request]**
    body : 
        messageId
        attestedDidDoc
end note

    TAS -> TAS: Signature Verification\
                \n* Verify Wallet Provider Signature\
                \n* Verify Individual Key Signature

    TAS -> TAS: (InvokedDidDoc)invDidDoc = {\
        \n   didDoc,\
        \n   controller = TAS Information,\
        \n   nonce = Generate nonce\
        \n }

    TAS -> TAS: Controller Signature\
        \n* signInvoke(invDidDoc)

    TAS -> BC++: DID Registration Request\n{invDidDoc}
        BC -> BC: Controller Signature Verification
        BC -> BC: Registration
    return OK

    TAS -> TAS: Save Mapping Information to DB\
        \n* walletId (Wallet Identifier)\
        \n* walletDid (Wallet DID)\
        \n* walletProviderDid (Wallet Provider DID)

return Wallet Registration Response
rnote right of WALLET #LightGray        
    **[M131_RES: Wallet Registration Response]**
    body : 
        txId
end note

WALLET --> CA--: OK

|||
|||
@enduml
