@startuml P131_user_register_ko

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 설정
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'=== Header and Footer ===
header OPEN-DID 기술 규격
footer
  	Page %page% of %lastpage% at %date("yyyy-MM-dd hh:mm:ss")
end footer

'=== 제목 ===
title
	<size:25>P132 : 사용자 등록</size>
end title

'=== 옵션 ===
autonumber "<b>(#)</b>"

'=== Panticipants ===
skinparam ParticipantPadding 20
skinparam BoxPadding 20
skinparam MaxMessageSize 500
skinparam MinClassWidth 80

actor "**사용자**" as USER

box 모바일 #OldLace
    participant "**월렛**" as WALLET <<Wallet>> #WhiteSmoke
    participant "**인가앱**" as CA <<App>> #WhiteSmoke    
end box

box TAS 사업자 #AliceBlue
    participant "**TAS**" as TAS <<WAS>> #WhiteSmoke
end box

box 신뢰저장소
    participant "**blockchain**" as BC <<Storage>> #WhiteSmoke
end box 

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 상수
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
!$refdoc = "별도 문서 참조"
!$doc = "데이터명세 문서 참조"

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 내용
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|||

== P132-1: 사용자 등록 시작 요청 ==
CA -> TAS++: 사용자 등록 시작 요청
rnote right of CA #Lavender        
    **[M132_REQ: 사용자 등록 시작 요청]**
    body : 
        messageId
end note

return 사용자 등록 시작 응답
rnote right of CA #Lavender        
    **[M132_RES: 사용자 등록 시작 응답]**
    body : 
        txId
end note

|||
== P132-2: ECDH 요청  ==
CA -> CA: ECDH 데이터 준비 및 서명\
            \n* (ReqEcdh)reqEcdh\
            \n   = ECDH 요청 생성

opt KeyAgreement 서명 ON
    CA -> WALLET ++: KeyAgreement 서명 요청\n{reqEcdh}
        WALLET -> WALLET: signKeyAgree(reqEcdh)
        note right
            실제 호출 시
            * 인가앱은 원문의 해시와 keyId를 전달
            * 월렛은 서명값만 응답
        end note
    return {reqEcdh}
end

CA -> TAS++ : ECDH 요청
rnote right of CA #Lavender
    **[M132_REQ : ECDH 요청]**
    body : 
        messageId
        txId
        reqEcdh
end note

    opt KeyAgreement 서명 ON
        TAS -> TAS: reqEcdh.proof 서명 검증
    end

    TAS -> TAS: ECDH 수행\
                \n* sesKey = 세션키\
                \n* (AccEcdh)accEcdh\
                \n   = ECDH 수락 생성

    opt KeyAgreement 서명  ON
        TAS -> TAS: signKeyAgree(accEcdh)
    end

return ECDH 응답
rnote right of CA #Lavender
    **[M132_RES : ECDH 응답]**
    body : 
        txId
        accEcdh
end note

opt KeyAgreement 서명  ON
    CA -> CA: accEcdh.proof 서명 검증
end

CA -> CA: ECDH 수행\n* sesKey = 세션키

|||
== P132-3: 서버토큰 생성 요청  ==
hnote over CA, WALLET #LimeGreen
    * purpose = "CreateDid"
    * (SignedWalletInfo)walletInfo = 월렛정보 생성
    * walletToken = 월렛토큰
end hnote

CA -> CA: * (AttestedAppInfo)caAppInfo\
        \n   = 서명된 앱정보 생성

CA -> CA: 서버토큰시드 생성\
        \n* (ServerTokenSeed)seed = {\
        \n     purpose = "CreateDid",\
        \n     walletInfo,\
        \n     caAppInfo\
        \n  }

CA -> TAS++ : 서버토큰 생성 요청
rnote right of CA #Lavender
    **[M132_REQ : 서버토큰 생성 요청]**
    body : 
        messageId
        txId
        seed
end note

    TAS -> TAS: 서명 검증\
            \n* 월렛서명 검증\
            \n* 인증앱 사업자 서명 검증

    TAS -> TAS: seed에서 정보 추출\
            \n* appId = 인가앱 식별자\
            \n* walletId = 월렛 식별자\
            \n* walletDid = 월렛 DID\
            \n* walletProviderDid = 월렛 사업자 DID

    TAS -> TAS: 등록된 월렛정보와 일치여부 확인

    TAS -> TAS: 서버토큰 생성 및 저장\
            \n* (ServerTokenData)std 생성\
            \n* serverToken = sha256(std)

    TAS -> TAS: 응답정보 암호화\
            \n* iv = IV 생성\
            \n* tmp = enc(std, sesKey, iv)\
            \n* encStd = multibase(tmp)


return 서버토큰 생성 응답
rnote right of CA #Lavender
    **[M132_RES : 서버토큰 생성 응답]**
    body : 
        txId
        iv
        encStd
end note

CA -> CA: 복호화(생략) 및 데이터 준비\
        \n* serverToken 계산

|||
== 사용자 KYC  ==
rnote across #white
    사용자가 KYC를 수행한 후, PII(Personally Identifiable Information)와 같은 식별자를 등록해야 함.
    이 과정은 본 규격에서 다루지 않음. 
end note

|||
== P132-4: 사용자 등록 요청  ==

CA -> WALLET ++: 사용자 DID 키 생성 요청\n{walletToken}
    WALLET -> WALLET: walletToken 검증

    USER -[#Blue]\ WALLET: PIN 입력
    WALLET -> WALLET: PIN 키 생성

    opt 사용자가 원할 경우
        USER -[#Blue]\ WALLET: 지문/안면 인식
        WALLET -> WALLET: BIO 키 생성
    end

    WALLET -> WALLET: 키교환용 키 생성
return OK

CA -> WALLET ++: 사용자 등록 요청\n{walletToken, serverToken}
    WALLET -> WALLET: walletToken 검증

    WALLET -> WALLET: (DidDoc)didDoc \
            \n  = DID Document 생성
    WALLET -> WALLET: (OwnerDidDoc)ownerDidDoc\
            \n  = 개별키서명(didDoc)
    WALLET -> WALLET: (SignedDidDoc)sgdDidDoc = {\
            \n   onwerDidDoc,\
            \n   wallet = 월렛 정보,\
            \n   nonce = nonce 생성\
            \n }
    WALLET -> WALLET: 월렛 서명\
            \n* signAssert(sgdDidDoc)

    WALLET -> TAS ++: 사용자 등록 요청
    rnote right of WALLET #Lavender
        **[M132_REQ : 사용자 등록 요청]**
        body:
            messageId
            txId
            serverToken
            signedDidDoc
    end note
        TAS -> TAS: serverToken 검증

        TAS -> TAS: 서명 검증\
            \n* 월렛 서명 검증\
            \n* 개별키 서명 검증
        
        TAS -> TAS: (InvokedDidDoc)invDidDoc = {\
            \n   didDoc,\
            \n   controller = TAS 정보,\
            \n   nonce = nonce 생성\
            \n }

        TAS -> TAS: Controller 서명\
            \n* signInvoke(invDidDoc)

        TAS -> BC ++: DID 등록 요청\n{invDidDoc}
            BC -> BC: Controller\n서명 검증
            BC -> BC: 등록
        return OK

        TAS -> TAS: 사용자 매핑정보 DB 저장\
                \n* pii (개인식별번호)\
                \n* holderDid (사용자 DID)\
                \n* walletId (월렛 식별자)\
                \n* appId (인가앱 식별자)
        return 사용자 등록 응답
        rnote right of WALLET #Lavender
            **[M132_REQ : 사용자 등록 응답]**
            body:
                txId
        end note
return OK


|||
== P132-5: 사용자 등록 완료  ==
CA -> TAS++: 사용자 등록 완료 요청
rnote right of CA #Lavender        
    **[M132_REQ: 사용자 등록 완료 요청]**
    body:
        messageId
        txId
        serverToken
end note

    TAS -> TAS: serverToken 검증
    TAS -> TAS: 세션정보 삭제 및 거래종료

return 사용자 등록 완료 응답
rnote right of CA #Lavender        
    **[M132_RES: 사용자 등록 완료 응답]**
    body:
        txId
end note

|||
|||
@enduml

