
@startuml update_vc_status_ko

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 설정
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'=== Header and Footer ===
header OPEN-DID 기술 규격
footer
  	Page %page% of %lastpage% at %date("yyyy-MM-dd hh:mm:ss")
end footer

'=== 제목 ===
title
	<size:25>VC 상태변경</size>
end title

'=== 옵션 ===
' 자동채번: ex) "<b>000." => 앞에 0을 채워 3자리 숫자로 표시
autonumber "<b>(#)</b>"
' 페이지 하단 participant box 숨기기
'hide footbox

'=== Panticipants ===
skinparam ParticipantPadding 20
skinparam BoxPadding 20
skinparam MaxMessageSize 500
skinparam MinClassWidth 80


box 발급서버 #AliceBlue
    participant "**ISSUER**" as ISSUER <<WAS>> #WhiteSmoke
end box
/' 
box 저장소통신서버 #AliceBlue
    participant "**TSS**" as TSS <<WAS>> #WhiteSmoke
end box 
'/
box 신뢰저장소
    participant "**blockchain**" as BC <<Storage>> #WhiteSmoke
end box 

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 상수
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 내용
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|||

== VC 상태변경 ==
activate ISSUER

ISSUER -> ISSUER : VC 상태변경 확인

ISSUER -> BC++ : VC 메타데이터 변경
rnote right of ISSUER #LightGray
    **[API_REQ : VC 메타 갱신 요청]**
    SignVcMeta
end note
    'TSS -> BC++ : VC 메타데이터 등록
    'return

return
rnote right of ISSUER #LightGray
    **[API_RES : VC 메타 갱신 응답]**
end note


|||
|||
@enduml

