@startuml issue_wallet_token_simple_ko

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 설정
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'=== Header and Footer ===
header OPEN-DID 기술 규격
footer
  	Page %page% of %lastpage% at %date("yyyy-MM-dd hh:mm:ss")
end footer

'=== 제목 ===
title
	<size:25>월렛토큰 생성</size>
end title

'=== 옵션 ===
autonumber "<b>(#)</b>"

'=== Panticipants ===
skinparam ParticipantPadding 20
skinparam BoxPadding 20
skinparam MaxMessageSize 500
skinparam MinClassWidth 80

box 모바일 #OldLace
    participant "**월렛**" as WALLET <<Wallet>> #WhiteSmoke
    participant "**인가앱**" as CA <<App>> #WhiteSmoke    
end box

box 신뢰저장소
    participant "**blockchain**" as BC <<Storage>> #WhiteSmoke
end box 

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 상수
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
!$refdoc = "별도 문서 참조"
!$doc = "데이터명세 문서 참조"

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 내용
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|||

== 월렛토큰 시드 생성  ==

CA -> WALLET++ : 월렛토큰 시드 생성 요청
WALLET --> CA--: 월렛토큰 시드

== 월렛토큰 데이터 생성  ==

rnote across #white
    월렛은 인가앱 사업자에게 월렛토큰 시드를 전달하여 월렛토큰 데이터 생성을 요청해야 한다.
    월렛토큰 데이터에는 사용자를 식별할 수 있는 값과 인가앱 사업자의 서명이 포함되어야 한다.

    이 과정은 본 규격에서 다루지 않는다.
end note

|||
== 월렛토큰 생성  ==
CA -> WALLET++ : 월렛토큰 생성 요청
WALLET -> WALLET: 난수 생성
WALLET -> WALLET: 월렛 토큰 생성 (월렛토큰 데이터, 난수)
WALLET --> CA--: 난수

rnote across #white
    월렛은 난수를 생성하고 월렛토큰 데이터와 결함하여 월렛토큰을 생성한다.
    월렛은 인가앱에게 난수만을 전달하며, 인가앱은 동일한 방식으로 난수와 월렛토큰 데이터를 사용해 월렛토큰을 생성한다.
end note

CA -> CA: 월렛 토큰 생성 (월렛토큰 데이터, 난수)

|||
|||
@enduml

