@startuml issue_wallet_token_simple

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Settings
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'=== Header and Footer ===
header OPEN-DID Technical Specification
footer
  	Page %page% of %lastpage% at %date("yyyy-MM-dd hh:mm:ss")
end footer

'=== Title ===
title
	<size:25>Create Wallet Token</size>
end title

'=== Options ===
autonumber "<b>(#)</b>"

'=== Participants ===
skinparam ParticipantPadding 20
skinparam BoxPadding 20
skinparam MaxMessageSize 500
skinparam MinClassWidth 80

box Mobile #OldLace
    participant "**Wallet**" as WALLET <<Wallet>> #WhiteSmoke
    participant "**Certified App**" as CA <<App>> #WhiteSmoke    
end box

box Trusted Storage
    participant "**blockchain**" as BC <<Storage>> #WhiteSmoke
end box 

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Constants
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
!$refdoc = "Refer to separate document"
!$doc = "Refer to data specification document"

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Content
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
||| 

== Wallet Token Seed Generation ==

CA -> WALLET++ : Request Wallet Token Seed Generation
WALLET --> CA--: Wallet Token Seed

== Wallet Token Data Generation ==

rnote across #white
    The wallet must send the wallet token seed to the certified app provider to request wallet token data generation.
    The wallet token data should include user-identifiable values and a signature from the certified app provider.

    This process is not covered in this specification.
end note


||| 
== Wallet Token Creation ==
CA -> WALLET++ : Request Wallet Token Creation
WALLET -> WALLET: Generate Random Number
WALLET -> WALLET: Create Wallet Token (Wallet Token Data, Random Number)
WALLET --> CA--: Random Number

rnote across #white
    The wallet generates a random number and combines it with the wallet token data to create the wallet token.
    The wallet sends only the random number to the authorization app, which then generates the wallet token using the same method with the random number and wallet token data.
end note

CA -> CA: Create Wallet Token (Wallet Token Data, Random Number)

||| 
||| 
@enduml
