@startuml P141_update_diddoc

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Settings
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'=== Header and Footer ===
header OPEN-DID Technical Specification
footer
  	Page %page% of %lastpage% at %date("yyyy-MM-dd hh:mm:ss")
end footer

'=== subject ===
title
	<size:25>P141 : User DID Document Update</size>
end title

'=== Options ===
autonumber "<b>(#)</b>"

'=== Panticipants ===
skinparam ParticipantPadding 20
skinparam BoxPadding 20
skinparam MaxMessageSize 500
skinparam MinClassWidth 80

actor "**User**" as USER

box Mobile #OldLace
    participant "**Wallet**" as WALLET <<Wallet>> #WhiteSmoke
    participant "**Certified App**" as CA <<App>> #WhiteSmoke    
end box

box TAS Provider #AliceBlue
    participant "**TAS**" as TAS <<WAS>> #WhiteSmoke
end box

box Trusted Storage
    participant "**blockchain**" as BC <<Storage>> #WhiteSmoke
end box 

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Constants
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
!$refdoc = "Refer to separate document"
!$doc = "Refer to data specification document"

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Content
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|||

== P141-1: User DID Document Update Start Request ==
CA -> TAS++: User DID Document Update Start Request
rnote right of CA #Lavender        
    **[M141_REQ: User DID Document Update Start Request]**
    body : 
        messageId
        did
end note

    TAS -> TAS: Check if the DID is in a modifiable state
    TAS -> TAS: authNonce = Generate nonce for DID Auth

return User DID Document Update Start Response
rnote right of CA #Lavender        
    **[M141_RES: User DID Document Update Start Response]**
    body : 
        txId
        authNonce
end note

|||
== P141-2: ECDH Request ==
CA -> CA: Prepare ECDH Data and Sign\
            \n* (ReqEcdh)reqEcdh\
            \n   = Generate ECDH Request

opt KeyAgreement Signature ON
    CA -> WALLET ++: KeyAgreement Signature Request\n{reqEcdh}
        WALLET -> WALLET: signKeyAgree(reqEcdh)
        note right
            During the actual call:
            * The certified app sends the hash of the original and the keyId
            * The wallet only responds with the signature value
        end note
    return {reqEcdh}
end

CA -> TAS++ : ECDH Request
rnote right of CA #Lavender
    **[M141_REQ : ECDH Request]**
    body : 
        messageId
        txId
        reqEcdh
end note

    opt KeyAgreement Signature ON
        TAS -> TAS: Verify reqEcdh.proof signature
    end

    TAS -> TAS: Perform ECDH\
                \n* sesKey = Session Key\
                \n* (AccEcdh)accEcdh\
                \n   = Generate ECDH Acceptance

    opt KeyAgreement Signature ONx
        TAS -> TAS: signKeyAgree(accEcdh)
    end

return ECDH Response
rnote right of CA #Lavender
    **[M141_RES : ECDH Response]**
    body : 
        txId
        accEcdh
end note

opt KeyAgreement Signature ON
    CA -> CA: Verify accEcdh.proof signature
end

CA -> CA: Perform ECDH\n* sesKey = Session Key

|||
== P141-3: Server Token Generation Request ==
hnote over CA, WALLET #LimeGreen
    * purpose = "UpdateDid"
    * (SignedWalletInfo)walletInfo = Generate wallet information
    * walletToken = Wallet token
end hnote

CA -> CA: * (AttestedAppInfo)caAppInfo\
        \n   = Generate signed app information

CA -> CA: Generate server token seed\
        \n* (ServerTokenSeed)seed = {\
        \n     purpose = "UpdateDid",\
        \n     walletInfo,\
        \n     caAppInfo\
        \n  }

CA -> TAS++ : Server Token Generation Request
rnote right of CA #Lavender
    **[M141_REQ : Server Token Generation Request]**
    body : 
        messageId
        txId
        seed
end note

    TAS -> TAS: Verify signatures\
            \n* Verify wallet signature\
            \n* Verify certified app provider signature

    TAS -> TAS: Extract information from seed\
            \n* appId = Certified app identifier\
            \n* walletId = Wallet identifier\
            \n* walletDid = Wallet DID\
            \n* walletProviderDid = Wallet provider DID

    TAS -> TAS: Check consistency with registered wallet information

    TAS -> TAS: Generate and store server token\
            \n* Generate (ServerTokenData)std\
            \n* serverToken = sha256(std)

    TAS -> TAS: Encrypt response information\
            \n* iv = Generate IV\
            \n* tmp = enc(std, sesKey, iv)\
            \n* encStd = multibase(tmp)

return Server Token Generation Response
rnote right of CA #Lavender
    **[M141_RES : Server Token Generation Response]**
    body : 
        txId
        iv
        encStd
end note

CA -> CA: Decrypt (omitted) and prepare data\
        \n* Calculate serverToken


|||
== P141-4: User DID Document Update Request ==

opt When adding a DID key
    CA -> WALLET ++: Request User DID Key Generation\n{walletToken}
        WALLET -> WALLET: Validate walletToken

        opt When adding a PIN key
            USER -[#Blue]\ WALLET: Enter PIN
            WALLET -> WALLET: Generate PIN key
        end
        opt When adding a BIO key
            USER -[#Blue]\ WALLET: Fingerprint/Face Recognition
            WALLET -> WALLET: Generate BIO key
        end
        opt When adding a BIO key
            WALLET -> WALLET: Generate key for key exchange
        end
    return OK
end

CA -> WALLET ++: Request User DID Document Update\n{walletToken, serverToken}
    WALLET -> WALLET: Validate walletToken

    WALLET -> WALLET: (DidDoc)didDoc \
            \n  = Generate DID Document
    note right
        The following items must be updated to the latest values:
        * updated: Last modification date
        * versionId: Incremented by +1 compared to the previous version
    end note

    WALLET -> WALLET: (OwnerDidDoc)ownerDidDoc\
            \n  = Sign individual keys (didDoc)
    WALLET -> WALLET: (SignedDidDoc)sgdDidDoc = {\
            \n   ownerDidDoc,\
            \n   wallet = wallet information,\
            \n   nonce = Generate nonce\
            \n }
    WALLET -> WALLET: Wallet signature\
            \n* signAssert(sgdDidDoc)

    WALLET -> WALLET: Prepare DID Auth data\
    \n* (DidAuth)didAuth = {\
    \n     did = Holder DID,\
    \n     authNonce\
    \n  }

    USER -[#Blue]\ WALLET: User authentication
    WALLET -> WALLET: signAuth(didAuth)

    WALLET -> TAS ++: User DID Document Update Request
    rnote right of WALLET #Lavender
        **[M141_REQ : User DID Document Update Request]**
        body:
            messageId
            txId
            serverToken
            didAuth
            signedDidDoc
    end note
        TAS -> TAS: Validate serverToken

        TAS -> TAS: Validate DID Auth\
                \n* Verify didAuth.proof\
                \n* Check if authNonce matches

        TAS -> TAS: Validate signatures\
            \n* Verify wallet signature\
            \n* Verify individual key signature
        
        TAS -> TAS: Validate DID comparison\
            \n* didDoc.did = M141_1_REQ.did\
            \n* didDoc.did = didAuth.did

        TAS -> TAS: (InvokedDidDoc)invDidDoc = {\
            \n   didDoc,\
            \n   controller = TAS information,\
            \n   nonce = Generate nonce\
            \n }

        TAS -> TAS: Controller signature\
            \n* signInvoke(invDidDoc)

        TAS -> BC ++: Request DID Registration\n{invDidDoc}
            BC -> BC: Verify Controller signature
            BC -> BC: Register
        return OK

        TAS -> TAS: Check user mapping information in DB\
                \n* holderDid (User DID)\
                \n* walletId (Wallet identifier)\
                \n* appId (Certified app identifier)
        return User DID Document Update Response
        rnote right of WALLET #Lavender
            **[M141_REQ : User DID Document Update]**
            body:
                txId
        end note
return OK


|||
== P141-5: User DID Document Update Completion ==
CA -> TAS++: User DID Document Update Completion Request
rnote right of CA #Lavender        
    **[M141_REQ: User DID Document Update Completion Request]**
    body:
        messageId
        txId
        serverToken
end note

    TAS -> TAS: Validate serverToken
    TAS -> TAS: Delete session information and end transaction

return User Registration Completion Response
rnote right of CA #Lavender        
    **[M141_RES: User DID Document Update Completion Request]**
    body:
        txId
end note

|||
|||
@enduml

