@startuml P310_submit_vp_simple

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Settings
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'=== Header and Footer ===
header OPEN-DID Technical Specification
footer
  	Page %page% of %lastpage% at %date("yyyy-MM-dd hh:mm:ss")
end footer

'=== Title ===
title
	<size:25>P310: VP Submission</size>
end title

'=== Options ===
autonumber "<b>(#)</b>"

'=== Participants ===
skinparam ParticipantPadding 20
skinparam BoxPadding 20
skinparam MaxMessageSize 500
skinparam MinClassWidth 80

box Mobile #OldLace
    participant "**Wallet**" as WALLET <<Wallet>> #WhiteSmoke
    participant "**Certified App**" as CA <<App>> #WhiteSmoke    
end box

box Verification Server #AliceBlue
    participant "**Verifier**" as SP <<WAS>> #WhiteSmoke
end box

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Content
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|||
== VP Offer Request  ==

rnote across #white
    The Certified App must receive the VP Offer request from the Verifier.
    However, the specific details of this process are not covered in this specification.
end note

== P310-1: VP Profile Request ==

CA -> SP++: VP Profile Request
rnote right of CA #Lavender        
    **[M310_REQ: VP Profile Request]**
end note

SP -> SP: VP Profile Creation / Signing

SP --> CA--: VP Profile Response
rnote right of CA #Lavender        
    **[M310_RES: VP Profile Response]**
end note

== P310-2: VP Submission  ==

rnote across #white
    The VP must be submitted in an encrypted form.
    The process of key exchange between the Certified App and Verifier for encryption and decryption has been omitted.
end note

CA -> SP++: VP Submission
rnote right of CA #Lavender        
    **[M310_REQ: VP Submission]**
end note

SP -> SP : VP Verification
SP --> CA--: VP Submission Result
rnote right of CA #Lavender        
    **[M310_RES: VP Submission Result]**    
end note

== VP Submission Result Confirmation ==

rnote across #white
    The entity that requested VP submission can request the VP submission result from the Verifier.
    However, the specific details of this process are not covered in this specification.
end note


|||
|||
@enduml
