
@startuml P131_register_wallet_ko

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 설정
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'=== Header and Footer ===
header OPEN-DID 기술 규격
footer
  	Page %page% of %lastpage% at %date("yyyy-MM-dd hh:mm:ss")
end footer

'=== 제목 ===
title
	<size:25>P131 : 월렛 등록</size>
end title

'=== 옵션 ===
autonumber "<b>(#)</b>"

'=== Panticipants ===
skinparam ParticipantPadding 20
skinparam BoxPadding 20
skinparam MaxMessageSize 500
skinparam MinClassWidth 80

box 모바일 #OldLace    
    participant "**월렛**" as WALLET <<Wallet>> #WhiteSmoke 
    participant "**인가앱**" as CA <<App>> #WhiteSmoke 
end box

box Wallet 사업자 #AliceBlue
    participant "**월렛 서비스**" as WP <<WAS>> #WhiteSmoke
end box

box TAS 사업자 #AliceBlue
    participant "**TAS**" as TAS <<WAS>> #WhiteSmoke
end box

box 신뢰저장소
    participant "**blockchain**" as BC <<Storage>> #WhiteSmoke
end box 

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 상수
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

!$refdoc = "별도 문서 참조"
!$doc = "데이터명세 문서 참조"


'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 내용
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|||

CA -> WALLET++: 월렛 생성 요청

== 허용된 CA 목록 조회 요청 ==
WALLET -> TAS++: 허용된 CA 목록 조회 요청
rnote right of WALLET #LightGray        
    **[API_REQ : 허용된 CA 목록 조회 요청]**
    query:
        wallet
end note

return 허용된 CA 목록 조회 응답
rnote right of WALLET #LightGray        
    **[API_RES : 허용된 CA 목록 조회 응답]**
    body:
        count
        items
end note

|||
== 월렛 생성 ==
WALLET -> WALLET: 월렛 초기화

|||
== 월렛 DID Document 생성 ==
WALLET -> WALLET: 월렛 키(Device Key) 생성

WALLET -> WALLET: (DidDoc)didDoc \
               \n  = DID Document 생성
WALLET -> WALLET: (OwnerDidDoc)ownerDidDoc\
               \n  = 개별키서명(didDoc)

WALLET -> WP ++: DID Document 서명 요청\n{ownerDidDoc}
    WP -> WP: walletId = 월렛 식별자 생성
    WP -> WP: (AttestedDidDoc)attDidDoc = {\
        \n   walletId,\
        \n   onwerDidDoc,\
        \n   provider = 월렛 사업자 정보,\
        \n   nonce = nonce 생성\
        \n }
    WP -> WP: 월렛 사업자 서명\
        \n* signAssert(attDidDoc)
    WP -> WP: 매핑 정보 DB 저장\
        \n* walletId (월렛 식별자)\
        \n* walletDid (월렛 DID)
return {attDidDoc}


|||
== P131 : 월렛 등록 요청 ==

WALLET -> TAS++: 월렛 등록 요청
rnote right of WALLET #LightGray        
    **[M131_REQ : 월렛 등록 요청]**
    body : 
        messageId
        attestedDidDoc
end note

    TAS -> TAS: 서명 검증\
                \n* 월렛 사업자 서명 검증\
                \n* 개별키 서명 검증
            
    TAS -> TAS: (InvokedDidDoc)invDidDoc = {\
        \n   didDoc,\
        \n   controller = TAS 정보,\
        \n   nonce = nonce 생성\
        \n }

    TAS -> TAS: Controller 서명\
        \n* signInvoke(invDidDoc)

    TAS -> BC ++: DID 등록 요청\n{invDidDoc}
        BC -> BC: Controller\n서명 검증
        BC -> BC: 등록
    return OK

    TAS -> TAS: 매핑 정보 DB 저장\
        \n* walletId (월렛 식별자)\
        \n* walletDid (월렛 DID)\
        \n* walletProviderDid (월렛 사업자 DID)

return 월렛 등록 응답
rnote right of WALLET #LightGray        
    **[M131_RES : 월렛 등록 응답]**
    body : 
        txId
end note

WALLET --> CA--: OK

|||
|||
@enduml

