@startuml usecase_issuer_group
rectangle "발급 사업자 집단" as issuers {
    actor :발급 사업자 #1: as issuer1
    actor :발급 사업자 #2: as issuer2
    actor :     ...      : as issuer3
    actor :발급 사업자 #N: as issuerN
}

issuers -> (발급 사업자 집단 설립)
issuers --> (대표 사업자 선정)
@enduml


