@startuml lifecycle_vc_plan
state ACTIVE: ACTIVATED
state INACTIVE: INACTIVATED
state REMOVED: REMOVED

[*] -> ACTIVE
ACTIVE -> INACTIVE
INACTIVE -> ACTIVE
ACTIVE -> REMOVED
INACTIVE -> REMOVED
REMOVED -> [*]

@enduml

