@startuml usecase_issuer_group
rectangle "Issuers Group" as issuers {
    actor :Issuer #1: as issuer1
    actor :Issuer #2: as issuer2
    actor :     ...     : as issuer3
    actor :Issuer #N: as issuerN
}

issuers -> (Establish Issuers Group)
issuers --> (Select Representative Issuer)
@enduml