@startuml proc_register_wallet
|월렛|
start
:**A1.** 월렛 생성;
:**A2.** 월렛 DID Document 생성;

|월렛 사업자|
:**A3.** 월렛 DID Document 서명;

|TAS|
:**A4.** 월렛 등록;
note right
    [월렛 → TAS]
    * Request Register Wallet
end note
stop
@enduml

--------------------------------------------------------------------------------

@startuml proc_reigster_user
start

:**B1.** 사용자 등록 시작 요청;
note right
    [인가앱 → TAS]
    * Propose Register User
end note

:**B2.** ECDH;
note right
    [인가앱 → TAS]
    * Request ECDH
end note

:**B3.** 월렛토큰, 서버토큰 생성;
note right
    [인가앱 → TAS]
    * Request Create Token
end note

:**B4.** 사용자 등록 요청;
note right
    [월렛 → TAS]
    * Request Register User
end note

:**B5.** 사용자 등록 완료;
note right
    [인가앱 → TAS]
    * Confirm Register User
end note

stop
@enduml

--------------------------------------------------------------------------------

@startuml proc_preparation
|발급 사업자 컨소시엄|
start
:**A1.** Claim 정의;
:**A2.** VC Schema 정의 및 게시;
:**A3.** Plan Manager 선정;
:**A4.** (Optional) 대표 발급자 선정;

|목록 사업자|
:**B1.** VC Plan 등록;
note right
    [목록 사업자 관리자 콘솔 및 API]
    * VC Plan 등록/수정/삭제
    * VC Plan 상태변경
end note

:**B2.** VC Plan 이슈어 등록;
note right
    [목록 사업자 관리자 콘솔 및 API]
    * 이슈어 등록/수정/삭제
    * 이슈어 상태변경
end note
stop
@enduml

--------------------------------------------------------------------------------

@startuml proc_issuance
start

fork
    partition "발급 사업자" {
        :**C1.1.** 발급 Offer 생성;
        :**C1.2.** 발급 Offer 발송(이메일, PUSH 등);
    }
fork again
    partition "인가앱" {
        :**C2.1.** VC Plan 검색 및 조회;
        note right
            [인가앱 → 목록 사업자]
            * List Category
            * Search VC Plan
            * List VC Plan
        end note

        :**C2.2.** 발급할 VC Plan 선택;
    }
end fork

:**D1.** 발급 시작 요청;
note right
    [인가앱 → TAS]
    * Propose Issue VC
end note

:**D2.** ECDH;
note right
    [인가앱 → TAS]
    * Request ECDH
end note

:**D3.** 월렛토큰, 서버토큰 생성;
note right
    [인가앱 → TAS]
    * Request Create Token
end note

:**D4.** Issue Profile 요청;
note right
    [인가앱 → TAS]
    * Request Issue Profile
end note

:**D5.** DID Auth 및 발급 요청;
note right
    [월렛 → TAS]
    * Request Issue VC
end note

:**D6.** 발급 완료;
note right
    [인가앱 → TAS]
    * Confirm Issue VC
end note

stop
@enduml

--------------------------------------------------------------------------------

@startuml proc_present
start

partition "Offer 단계 (Offering)" {
    :**B1.** 제출 Offer payload 생성;
    note right: out of scope

    :**B2.** 제출 Offer 송신;
    note right: out of scope

    :**B3.** 제출 Offer 수신;
    note right: out of scope
}

partition "제출 단계 (Presentation)" {
    :**C1.** VerifyProfile 요청;
    note right
        [인가앱, 응대장치 → 검증 사업자]
        * Request Profile
    end note

    :**C2.** VP 제출;
    note right
        [인가앱, 응대장치 → 검증 사업자]
        * Request Verify
    end note
}

stop
@enduml

