@startuml proc_wallet_token
title
	<size:25>Wallet Token Creation</size>
end title

participant "**Wallet**" as wal <<Wallet>>
participant "**Certified App**" as ca <<App>>
participant "**Certified App Service**" as cap <<Server>>
autonumber "<b>(#)</b>"

ca -> wal++: Request WalletTokenSeed 
wal --> ca--: Provide WalletTokenSeed
ca -> cap++: Request WalletTokenData (WalletTokenSeed)
cap --> ca--: Provide WalletTokenData
ca -> wal++: Request WalletToken Creation (WalletTokenData)
wal -> wal: Generate Nonce
wal -> wal: Create WalletToken by combining WalletTokenData and Nonce (WalletTokenData, Nonce)
wal -> wal: Store WalletToken
wal --> ca--: Provide Nonce
ca -> ca: Create WalletToken by combining WalletTokenData and Nonce
ca -> wal: Submit WalletToken when using Wallet

@enduml