@startuml "diddoc_lifecycle"
state ACTIVATED
state DEACTIVATED
state REVOKED
state TERMINATED : Termination Start Date

[*] -> ACTIVATED
ACTIVATED -> DEACTIVATED
ACTIVATED -> REVOKED

DEACTIVATED -> ACTIVATED
DEACTIVATED -> REVOKED

REVOKED -> TERMINATED
TERMINATED -> [*]
@enduml

```plantuml
@startuml diddoc_proc
'left to right direction
|Holder|
start
:Create DID Document Body;
:Generate Holder Signature;

|Controller|
:Verify Holder Signature and Remove it from Body;
:Store DID Document Body in Trust Repository;
stop
@enduml
```
