@startuml proc_server_token
title
	<size:25>Server Token Creation</size>
end title

participant "**Wallet**" as wal <<Wallet>>
participant "**Certified App**" as ca <<App>>
participant "**Certified App Service**" as cap <<Server>>
participant "**TA**" as ta <<Server>>
autonumber "<b>(#)</b>"

ca -> wal++: Request SignedWalletInfo 
wal --> ca--: Provide SignedWalletInfo
ca -> cap++: Request AttestedAppInfo
cap --> ca--: Provide AttestedAppInfo
ca -> ca: Generate ServerTokenSeed (SignedWalletInfo, AttestedAppInfo)
ca -> ta++: Request ServerToken (ServerTokenSeed)
ta -> ta: Generate ServerTokenData (ServerTokenSeed)
ta -> ta: Generate ServerToken (ServerTokenData)
ta -> ta: Create IV
ta -> ta: Encrypt ServerTokenData (SessionKey, IV)
note left: The TA and the Certified App have already exchanged session keys before issuing the server token.
ta --> ca--: Provide Encrypted ServerTokenData (IV)
ca -> ca: Decrypt ServerTokenData
ca -> ca : Generate ServerToken (ServerTokenData)
ca -> ta: Submit ServerToken upon TA request

@enduml