@startuml proc_register_wallet
|Wallet|
start
:**A1.** Create Wallet;
:**A2.** Create Wallet DID Document;

|Wallet Service Provider|
:**A3.** Sign Wallet DID Document;

|TAS|
:**A4.** Register Wallet;
note right
    [Wallet → TAS]
    * Request Register Wallet
end note
stop
@enduml

--------------------------------------------------------------------------------

@startuml proc_reigster_user
start

:**B1.** Request Start User Registration;
note right
    [CApp → TAS]
    * Propose Register User
end note

:**B2.** ECDH;
note right
    [CApp → TAS]
    * Request ECDH
end note

:**B3.** Create Wallet Token, Server Token;
note right
    [CApp → TAS]
    * Request Create Token
end note

:**B4.** Request User Registration;
note right
    [Wallet → TAS]
    * Request Register User
end note

:**B5.** Complete User Registration;
note right
    [CApp → TAS]
    * Confirm Register User
end note

stop
@enduml

--------------------------------------------------------------------------------

@startuml proc_preparation
|Issuing Service Consortium|
start
:**A1.** Define Claim;
:**A2.** Define and Publish VC Schema;
:**A3.** Select Plan Manager;
:**A4.** (Optional) Select Representative Issuer;

|List Service Provider|
:**B1.** Register VC Plan;
note right
    [List Service Provider Admin Console and API]
    * Register/Modify/Delete VC Plan
    * Change VC Plan Status
end note

:**B2.** Register VC Plan Issuer;
note right
    [List Service Provider Admin Console and API]
    * Register/Modify/Delete Issuer
    * Change Issuer Status
end note
stop
@enduml

--------------------------------------------------------------------------------

@startuml proc_issuance
start

fork
    partition "Issuer" {
        :**C1.1.** Create Issuance Offer;
        :**C1.2.** Send Issuance Offer (Email, PUSH, etc.);
    }
fork again
    partition "CApp" {
        :**C2.1.** Search and View VC Plan;
        note right
            [CApp → List Service Provider]
            * List Category
            * Search VC Plan
            * List VC Plan
        end note

        :**C2.2.** Select VC Plan to Issue;
    }
end fork

:**D1.** Request Start Issuance;
note right
    [CApp → TAS]
    * Propose Issue VC
end note

:**D2.** ECDH;
note right
    [CApp → TAS]
    * Request ECDH
end note

:**D3.** Create Wallet Token, Server Token;
note right
    [CApp → TAS]
    * Request Create Token
end note

:**D4.** Request Issue Profile;
note right
    [CApp → TAS]
    * Request Issue Profile
end note

:**D5.** DID Auth and Request Issuance;
note right
    [Wallet → TAS]
    * Request Issue VC
end note

:**D6.** Complete Issuance;
note right
    [CApp → TAS]
    * Confirm Issue VC
end note

stop
@enduml

--------------------------------------------------------------------------------

@startuml proc_present
start

partition "Offering Stage" {
    :**B1.** Create Presentation Offer payload;
    note right: out of scope

    :**B2.** Send Presentation Offer;
    note right: out of scope

    :**B3.** Receive Presentation Offer;
    note right: out of scope
}

partition "Presentation Stage" {
    :**C1.** Request VerifyProfile;
    note right
        [CApp, Service Device → Verifier]
        * Request Profile
    end note

    :**C2.** Submit VP;
    note right
        [CApp, Service Device → Verifier]
        * Request Verify
    end note
}

stop
@enduml
