@startuml "diddoc_lifecycle"
state ACTIVATED
state DEACTIVATED
state REVOKED
state TERMINATED : 말소 시작일자

[*] -> ACTIVATED
ACTIVATED -> DEACTIVATED
ACTIVATED -> REVOKED

DEACTIVATED -> ACTIVATED
DEACTIVATED -> REVOKED

REVOKED -> TERMINATED
TERMINATED -> [*]
@enduml

```plantuml
@startuml diddoc_proc
'left to right direction
|Holder|
start
:DID Document 본문 생성;
:Holder 서명 생성;

|Controller|
:Holder 서명 검증 후 본문에서 제거;
:신뢰저장소에 DID Document 본문 저장;
stop
@enduml
```
