
@startuml
participant app as "Client App"
participant tas as "TAS Server"

app ->> tas : PII Registration Request (PII)
tas -->> app : Response (Whether Already Registered)

alt When using an existing wallet
    app ->> tas : Request to use existing wallet
   note right of tas : File wallet cannot use existing wallet
   note right of tas : App wallet cannot use existing wallet if the device is different from the previous one
    tas -> tas : Update information (user, app)
    tas -->> app : OK
else When registering a new wallet
    app ->> tas : DIDDoc Registration Request
    tas -> tas : Revoke existing wallet, DIDDoc
    tas -> tas : Update information (user, wallet, app)
    tas -->> app : OK
end

app ->> tas : Verification Request
tas -->> app : OK
@enduml