@startuml issue_server_token_simple_ko

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 설정
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'=== Header and Footer ===
header OPEN-DID 기술 규격
footer
  	Page %page% of %lastpage% at %date("yyyy-MM-dd hh:mm:ss")
end footer

'=== 제목 ===
title
	<size:25>서버토큰 생성</size>
end title

'=== 옵션 ===
autonumber "<b>(#)</b>"

'=== Panticipants ===
skinparam ParticipantPadding 20
skinparam BoxPadding 20
skinparam MaxMessageSize 500
skinparam MinClassWidth 80

box 모바일 #OldLace
    participant "**월렛**" as WALLET <<Wallet>> #WhiteSmoke
    participant "**인가앱**" as CA <<App>> #WhiteSmoke    
end box

box 인가앱 사업자 #AliceBlue
    participant "**CAS**" as CAS <<WAS>> #WhiteSmoke
end box

box TAS 사업자 #AliceBlue
    participant "**TAS**" as TAS <<WAS>> #WhiteSmoke
end box

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 상수
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
!$refdoc = "별도 문서 참조"
!$doc = "데이터명세 문서 참조"

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 내용
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|||

== 서명된 월렛 정보 요청  ==
CA -> WALLET ++ : 서명된 Wallet 정보 요청 {월렛토큰}
WALLET -> WALLET: 난수 생성
WALLET -> WALLET : Wallet 정보 서명 (Wallet ID, 난수)
WALLET --> CA--: 서명된 Wallet 정보 전달

|||
== 서명된 앱 정보 요청  ==
rnote across #white
    인가앱은 로그인 또는 유사한 과정을 통해 인가앱 서버와 이미 세션을 맺고 있어야 한다.
    그러나 이 과정의 구체적인 내용은 본 규격에서 다루지 않는다.
end note

CA -> CAS ++ : 서명된 앱 정보 요청
CAS -> CAS : 난수 생성
CAS -> CAS : 앱 정보 서명 (인가앱 ID, 난수)
CAS --> CA--: 서명된 앱 정보 전달

|||
== 서버토큰 데이터 생성 요청  ==
CA -> CA: 서버토큰 시드 생성 (서명된 Wallet 정보, 서명된 앱 정보)

CA -> TAS++ : 서버토큰 데이터 요청 (서버토큰 시드)
TAS -> TAS: 서버토큰 데이터 생성 (서버토큰 시드)
TAS -> TAS: 서버토큰 생성 (서버토큰 데이터)
TAS --> CA--: 암호화된 서버토큰 데이터 전달

rnote across #white
    암복호화를 위해 CA와 TAS가 키를 교환 하는 과정은 생략함
end note

|||
== 서버토큰 생성  ==
CA -> CA: 서버토큰 데이터 복호화
CA -> CA: 서버토큰 생성 (서버토큰 데이터)

|||
|||
@enduml

