
@startuml update_vc_status_simple_ko

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 설정
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'=== Header and Footer ===
header OPEN-DID 기술 규격
footer
  	Page %page% of %lastpage% at %date("yyyy-MM-dd hh:mm:ss")
end footer

'=== 제목 ===
title
	<size:25>VC 상태변경</size>
end title

'=== 옵션 ===
' 자동채번: ex) "<b>000." => 앞에 0을 채워 3자리 숫자로 표시
autonumber "<b>(#)</b>"
' 페이지 하단 participant box 숨기기
'hide footbox

'=== Panticipants ===
skinparam ParticipantPadding 20
skinparam BoxPadding 20
skinparam MaxMessageSize 500
skinparam MinClassWidth 80

box Issuer 관리자
    actor "**Issuer Admin**" as ADMIN #WhiteSmoke
end box

box 발급 사업자 #AliceBlue
    participant "**ISSUER**" as ISSUER <<WAS>> #WhiteSmoke
end box

box 신뢰저장소
    participant "**blockchain**" as BC <<Storage>> #WhiteSmoke
end box 

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 상수
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 내용
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|||

== VC 상태변경 ==
rnote across #white
    Admin은 관리자 사이트 또는 다른 인터페이스를 통해 ISSUER에게 VC 상태변경을 요청해야 함.
    이 과정은 본 규격에서 다루지 않음. 
end note

ADMIN -> ISSUER++: VC 상태변경 요청
rnote right of ADMIN #Lavender        
    **[API_REQ : VC 상태변경 요청]**
end note

ISSUER -> BC: VC 메타데이터 변경

ISSUER --> ADMIN--: VC 상태변경 응답
rnote right of ADMIN #Lavender        
    **[API_REQ : VC 상태 변경 응답]**
end note

|||
|||
@enduml

