@startuml create_wallet_token

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Configuration
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'=== Header and Footer ===
header OPEN-DID Technical Specification
footer
    Page %page% of %lastpage% at %date("yyyy-MM-dd hh:mm:ss")
end footer

'=== Title ===
title
    <size:25>Create Wallet Token</size>
end title

'=== Option ===
' Autonumber: ex) "<b>000.</b>" => Display as a 3-digit number with leading zeros
autonumber "<b>(#)</b>"
' Hide the participant box at the bottom of the page
'hide footbox

'=== Participants ===
skinparam ParticipantPadding 20
skinparam BoxPadding 20
skinparam MaxMessageSize 500
skinparam MinClassWidth 80



box Mobile #OldLace
    participant "**Wallet**" as WALLET <<Wallet>> #WhiteSmoke
    participant "**Certified App**" as CA <<App>> #WhiteSmoke    
end box

box Trust Repository
    participant "**blockchain**" as BC <<Storage>> #WhiteSmoke
end box

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Constant
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
!$refdoc = "Refer to a separate document"
!$doc = "Refer to the data specification document"

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Content
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|||


== Create Wallet Token ==

activate CA

CA -> WALLET++ : Request tmpToken creation {purpose, pkgname, userId}
    WALLET -> WALLET : Create nonce 
    WALLET -> WALLET : Create tmpToken (TmpToken), expiration time
return {TmpToken}
rnote right of WALLET #MintCream
    **TmpToken** : Reference to Data Specification document
    TmpToken = 
        (nonce | expTime | purpose | pkgname | userId)
end note

group Created by CApp Server
    CA -> CA : Create signature with tmpToken and User ID (User Identification for user lookup)

    CA -> CA : Create Wallet Token Request data \n(ReqWalletToken) 
    rnote right of CA #MintCream
        **ReqWalletToken** : Reference to Data Specification document
        TmpToken | PII | Proof
        Proof = sign(TmpToken | PII, CAP_PrivateKey)

        CAP: CApp Provider (CApp Server)
    end note
end

CA -> WALLET++ : Request WalletToken creation \n{ReqWalletToken}
    WALLET -> BC++ : Retrieve CAP DID Document
    rnote right of WALLET #LightGray
        **[API_REQ :Request to Retrieve DID Document]**
        did
    end note

    return
    rnote right of WALLET #LightGray
        **[API_RES : Response to DID Document Retrieval]**
        DidDoc
    end note
    rnote right of WALLET #MintCream    
        **DidDoc** : $refdoc
    end note

    WALLET -> WALLET : Signature Verification
    WALLET -> WALLET : Generate resultNonce (resultNonce)

    WALLET -> WALLET : Create WalletToken {walletToken}
    rnote right of WALLET #MintCream
        **walletToken**
        walletToken =
            sha256(ReqWalletToken | resultNonce)
    end note

    return {resultNonce}
    note right of WALLET : Apply resultNonce transmission (4/18 reviewed by Senior Executive)

    CA -> CA : Create WalletToken {walletToken}
    rnote right of CA #MintCream
        **walletToken**
        walletToken = 
            sha256(ObjReqWalletToken | resultNonce)
    end note







|||
|||
@enduml
