
@startuml P110_register_tas_ko

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 설정
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'=== Header and Footer ===
header OPEN-DID 기술 규격
footer
  	Page %page% of %lastpage% at %date("yyyy-MM-dd hh:mm:ss")
end footer

'=== 제목 ===
title
	<size:25>P110 : TAS 등록</size>
end title

'=== 옵션 ===
autonumber "<b>(#)</b>"

'=== Panticipants ===
skinparam ParticipantPadding 20
skinparam BoxPadding 20
skinparam MaxMessageSize 500
skinparam MinClassWidth 80

box TAS 관리자
    actor "**TAS Admin**" as ADMIN #WhiteSmoke
end box

box TAS 사업자 #AliceBlue
    participant "**TAS**" as TAS <<WAS>> #WhiteSmoke
end box


box 신뢰저장소
    participant "**blockchain**" as BC <<Storage>> #WhiteSmoke
end box 
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 상수
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
!$refdoc = "별도 문서 참조"
!$doc = "데이터명세 문서 참조"


'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 내용
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|||

== TAS DID Document 등록  ==
rnote across #white
    TAS DID Document 등록은 본 규격에서 다루지 않음.
end note

|||

== P110 : TAS 등록 ==
rnote across #white
    TAS Admin은 사전에 password를 전달 받아야 한다.
end note
ADMIN -> TAS++: TAS 등록 요청
rnote right of ADMIN #LightGray        
    **[M110_REQ : TAS 등록 요청]**
    body : 
        messageId
        password
end note

    TAS -> TAS: vc: 가입증명서VC 발급
    rnote right of TAS #MintCream
        **가입증명서VC**: $refdoc
    end note

    TAS -> TAS: vcMeta: 가입증명서VC 메타데이터 생성
    rnote right of TAS #MintCream
        **vcMeta** : $doc
    end note

    TAS -> TAS: 가입증명서 VC 게시\
            \n* certVcRef = 가입증명서 VC URL

    TAS -> BC++ : vcMeta 등록 {vcMeta}
    return OK

return TAS 등록 응답
rnote right of ADMIN #LightGray        
    **[M110_RES : TAS 등록 응답]**
    body : 
        certVcRef
end note

|||
|||
@enduml

