
@startuml P310_submit_vp_ko
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 설정
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'=== Header and Footer ===
header OPEN-DID 기술 규격
footer
  	Page %page% of %lastpage% at %date("yyyy-MM-dd hh:mm:ss")
end footer

'=== 제목 ===
title
	<size:25>P310 : VP 제출 </size>
end title

'=== 옵션 ===
' 자동채번: ex) "<b>000." => 앞에 0을 채워 3자리 숫자로 표시
autonumber "<b>(#)</b>"
' 페이지 하단 participant box 숨기기
'hide footbox

'=== Panticipants ===
skinparam ParticipantPadding 20
skinparam BoxPadding 20
skinparam MaxMessageSize 500
skinparam MinClassWidth 80



box 모바일 #OldLace
    participant "**월렛**" as WALLET <<Wallet>> #WhiteSmoke
    participant "**인가앱**" as CA <<App>> #WhiteSmoke    
end box

box 검증서버 #AliceBlue
    participant "**Verifier**" as SP <<WAS>> #WhiteSmoke
end box


box 신뢰저장소
    participant "**blockchain**" as BC <<Storage>> #WhiteSmoke
end box 

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 상수
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

!$refdoc = "별도 문서 참조"
!$doc = "데이터명세 문서 참조"

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' 내용
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|||


== Offer 요청  ==

rnote across #white    
    Offer단계에서는 표준 API를 정의하지 않고 payload에 대한 데이터 형식만 규정되어있음.
    Offer를 어떤 방식으로 전달할지는 본 문서의 범위 밖이다.
end note

== P310-1 : Profile 요청 ==
activate CA


CA -> SP++ : Profile 요청(Request Profile)
rnote right of CA #Lavender
    **[M310_Req : Profile 요청]**    
    body : 
        messageId
        offerId
        verifierTxId
end note

SP -> SP : offerId 유효성 검사

SP -> SP : Profile 관련 데이터 준비\
            \n* verifierNonce = 제출용 nonce 생성\
            \n* (ReqE2e) reqE2e = E2E 요청 정보 생성
SP <-> BC : Verifier DID Doc 조회 / 응답


rnote right of SP #MintCream    
    **DidDoc** : $doc
end note
SP -> SP : Verify Profile 생성 / 서명
rnote right of SP #MintCream    
    **VerifyProfile** : $doc
end note

return
rnote right of CA #Lavender
    **[M310_Res : Profile 응답]**
    body : 
        verifyProfile
        veirifierTxId
end note

== Profile 검증 ==

CA <-> BC : Verifier DID Doc 조회 / 응답

rnote right of CA #MintCream    
    **DidDoc** : $doc
end note

CA -> CA : VerifyProfile 서명 검증
rnote right of CA #MintCream    
    **VerifyProfile** : $doc
end note

CA -> CA : 사용자 제출 정보 확인


== 월렛 토큰 생성 ==

rnote over WALLET, CA #white
    월렛 토큰 생성 : 인가앱 -> 월렛
end note


== VP 생성 ==

CA -> WALLET++ : VP 생성 요청 \n{VerifyProfile, \n사용자 선택 제출 정보}
WALLET -> WALLET : VP 생성 (VP)
rnote right of WALLET #MintCream    
    **VP** : $refdoc
end note

WALLET -> WALLET : 사용자 인증
WALLET -> WALLET : VP 서명 생성 \n(VpProof)
rnote right of WALLET #MintCream    
    **VpProof** : $doc
end note

WALLET -> WALLET : 임시키 쌍 생성 \n세션키 생성
WALLET -> WALLET : VP 암호화 \n(encVpProof)
rnote right of WALLET #MintCream    
    encVpProof = multibase(enc(iv, VpProof, seskey))

    * iv 적용은 KDF 방식에 따라 변경
end note

WALLET -> WALLET : VP 메시지 생성 \n(VpMsg)
rnote right of WALLET #MintCream    
    **VpMsg** : $doc    
end note


return VP 생성 요청 응답 \n{VpMsg}



== P310-2 : eVP 제출 및 검증 ==

CA -> SP++ : eVP(암호화 Vp) 검증 요청
rnote right of CA #Lavender
    **[M310_Req : eVP(암호화 Vp) 제출]**    
    body : 
        messageId
        verifierTxId
        accE2e
        VpMsg(enc)
end note

SP -> SP : 거래코드 조회
SP -> SP : E2e ECDH 수행\
        \n* accE2e.proof가 있으면 검증\
        \n* e2eKey = 암호화키 생성\
        \n* iv = accE2e.iv\
        
SP -> SP : eVP 복호화\
        \n* vp = decrypt(encVp, e2eKey, iv)\

SP -> SP : AuthType / nonce 일치여부 확인

SP <-> BC : Holder / Issuer DID Doc 조회
rnote right of SP #MintCream    
    **DidDoc** : $doc
end note

SP -> SP : VP 서명 검증\
        \n* vp.proof 검증\
        \n* VC 생애주기 유효성 확인\
        \n* VC 내 Issuer 서명 검증\
        

return
rnote right of CA #Lavender
    **[M310_Res : eVP 검증 응답]**      
        body : 
            verifierTxId        
end note


|||
|||
@enduml

