@startuml P120_register_entity_simple

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Settings
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'=== Header and Footer ===
header OPEN-DID Technical Specification
footer
  	Page %page% of %lastpage% at %date("yyyy-MM-dd hh:mm:ss")
end footer

'=== Title ===
title
	<size:25>P120: Entity Registration</size>
end title

'=== Options ===
autonumber "<b>(#)</b>"

'=== Participants ===
skinparam ParticipantPadding 20
skinparam BoxPadding 2
skinparam MaxMessageSize 500
skinparam MinClassWidth 80


box Entity Provider #AliceBlue
    participant "**Entity**" as ENT <<WAS>> #WhiteSmoke
end box

box TAS Provider #AliceBlue
    participant "**TAS**" as TAS <<WAS>> #WhiteSmoke
end box

box Trusted Storage
    participant "**blockchain**" as BC <<Storage>> #WhiteSmoke
end box 

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Constants
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
!$refdoc = "Refer to separate document"
!$doc = "Refer to data specification document"


'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Content
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
||| 

== Entity DID Document Registration ==
rnote across #white
    Entity DID Document registration is not covered in this specification. 
end note

||| 

== P120-1: Entity Registration Start Request ==
ENT -> TAS++ : Entity Registration Start Request
rnote right of ENT #Lavender
    **[M120_REQ: Entity Registration Start Request]**
end note

TAS --> ENT--: Entity Registration Start Response
rnote right of ENT #Lavender
    **[M120_RES: Entity Registration Start Response]**
end note

||| 
== P120-2: ECDH Request ==
ENT -> TAS++ : ECDH Request
rnote right of ENT #Lavender
    **[M120_REQ: ECDH Request]**
end note

TAS --> ENT--: ECDH Response
rnote right of ENT #Lavender
    **[M120_RES: ECDH Response]**
end note

||| 
ENT <--> TAS : Mutual Authentication and Key Exchange

||| 
== P120-3: Entity Registration Request ==
ENT -> TAS++ : Entity Registration Request
rnote right of ENT #Lavender
    **[M120_REQ: Entity Registration Request]**
end note

TAS -> TAS: Create Entity Membership Certificate VC
TAS -> BC : Register Membership Certificate VC Metadata

TAS --> ENT--: Entity Registration Response
rnote right of ENT #Lavender
    **[M120_RES: Entity Registration Response]**
    body:
        Encrypted Entity Membership Certificate VC
end note

||| 
== P120-4: Entity Registration Completion ==
ENT -> TAS++ : Entity Registration Completion Request
rnote right of ENT #Lavender
    **[M120_REQ: Entity Registration Completion Request]**
end note

TAS --> ENT--: Entity Registration Completion Response
rnote right of ENT #Lavender
    **[M120_RES: Entity Registration Completion Response]**
end note

|||
|||
@enduml
