
@startuml P210_issue_vc

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Settings
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
'=== Header and Footer ===
header OPEN-DID Technical Specification
footer
  	Page %page% of %lastpage% at %date("yyyy-MM-dd hh:mm:ss")
end footer

'=== Title ===
title
	<size:25>P210: Issue VC</size>
end title

'=== Options ===
autonumber "<b>(#)</b>"

'=== Panticipants ===
skinparam ParticipantPadding 20
skinparam BoxPadding 20
skinparam MaxMessageSize 500
skinparam MinClassWidth 80


actor USER

box Mobile #OldLace
    participant "**Wallet**" as WALLET <<Wallet>> #WhiteSmoke
    participant "**CA**" as CA <<App>> #WhiteSmoke    
end box

box TAS Server #AliceBlue
    participant "**TAS**" as TAS <<WAS>> #WhiteSmoke
end box

box Issuer Server #AliceBlue
    participant "**Issuer**" as ISSUER <<WAS>> #WhiteSmoke
end box
/' 
box Storage Communication Server #AliceBlue
    participant "**TSS**" as TSS <<WAS>> #WhiteSmoke
end box 
'/
box Trusted Storage
    participant "**blockchain**" as BC <<Storage>> #WhiteSmoke
end box


'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Constants
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

!$refdoc = "Refer to separate document"
!$doc = "Refer to data specification document"

'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
' Content
'- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|||


== P210-1 : VC Issuance Preparation ==
alt Issuer Initiate [Request Offer]
    USER -> TAS++: Request VC offer
    rnote right of CA #LightGray   
        **[API_REQ : Request VC offer]**
    end note
    TAS -> ISSUER++: Request VC offer
        return VC offer response
    TAS --> USER--: VC offer response
    rnote right of CA #LightGray   
        **[API_RES : VC offer response]**
    end note
    CA -> USER: Confirm Offer
else User Initiate [Request VC Plan ID]
    CA -> TAS++: Request VC Plan ID List
    rnote right of CA #LightGray   
        **[API_REQ : Request VC Plan ID List]**
    end note
    activate CA
    return VC Plan ID List response
    rnote right of CA #LightGray   
        **[API_RES : VC Plan ID List response]**
    end note
end
== P210-2 : VC Issuance Start Request ==
CA -> TAS++: Issue VC start request
    rnote right of CA #Lavender
        **[M210_REQ : Issue VC start request]**
    end note
    TAS -> ISSUER++: Issue VC start request
    return Issue VC start response
return Issue VC start response
rnote right of CA #Lavender
    **[M210_RES : Issue VC start response]**
end note

== P210-3 ECDH Request ==
CA -> TAS++ : ECDH Request
rnote right of CA #Lavender
    **[M210_REQ : ECDH Request]**
end note

TAS --> CA--: ECDH Response
rnote right of CA #Lavender
    **[M210_RES : ECDH Response]**
end note

== P210-4 Server Token Generation ==
rnote across #white
    The process of server token generation is not covered in this specification.
    Refer to `issue_server_token_simple`
end note

== P210-5 : Issue Profile Request ==
CA -> TAS++: Issue Profile Request
    rnote right of CA #Lavender
        **[M210_REQ : Issue Profile Request]**
    end note
    TAS -> ISSUER++: Issue Profile Request
    return Issue Profile Response
return Issue Profile Response
rnote right of CA #Lavender
    **[M210_RES : VC issuance start response]**
end note

== P210-6 : Issue VC Request ==
CA -> WALLET++: Issue VC request 
    WALLET -> TAS++: Issue VC request
        rnote right of CA #Lavender
            **[M210_REQ : Issue VC request]**
        end note
        TAS -> ISSUER++: Issue VC request
            ISSUER -> ISSUER: Issue VC
            ISSUER -> BC: Register VC Meta
            ISSUER -> ISSUER: VC<sub>enc</sub>=VC E2E encryption
        return VC<sub>enc</sub> response
    return VC<sub>enc</sub> response
    rnote right of CA #Lavender
        **[M210_RES : VC response]**
    end note
    WALLET -> WALLET: VC=VC<sub>enc</sub> E2E decryption
    WALLET -> WALLET: Store VC
return Result

== P210-7 : Issue VC Completion ==
CA -> TAS++: Request Issue VC completion
    rnote right of CA #Lavender
        **[M210_REQ : Request Issue VC completion]**
    end note
    TAS -> ISSUER++: Request Issue VC completion
    return VC issuance completion response
return VC issuance completion response
rnote right of CA #Lavender
    **[M210_RES : Issue VC completion response]**
end note
deactivate CA

@enduml
