@startuml
participant app as "Client App"
participant tas as "TAS Server"

app ->> tas : PII Registration Request (PII)
tas -->> app : Response (Whether Already Registered)

app ->> tas : DIDDoc Registration Request

note right of tas : In the case of a File Wallet, a new wallet must be used if the app is reinstalled.

tas -> tas : Revoke existing wallet and DIDDoc
tas -> tas : Update information (user, wallet, app)


app ->> tas : Verification Request
tas -->> app : OK
@enduml