@startuml proc_server_token
title
	<size:25>서버토큰 생성</size>
end title

participant "**월렛**" as wal <<Wallet>>
participant "**인가앱**" as ca <<App>>
participant "**인가앱 서비스**" as cap <<Server>>
participant "**TA**" as ta <<Server>>
autonumber "<b>(#)</b>"

ca -> wal++: SignedWalletInfo 요청 
wal --> ca--: SignedWalletInfo 전달
ca -> cap++: AttestedAppInfo 요청
cap --> ca--: AttestedAppInfo 전달
ca -> ca: ServerTokenSeed 생성 (SignedWalletInfo, AttestedAppInfo)
ca -> ta++: ServerToken 생성 요청 (ServerTokenSeed)
ta -> ta: ServerTokenData 생성 (ServerTokenSeed)
ta -> ta: ServerToken 생성 (ServerTokenData)
ta -> ta: IV 생성
ta -> ta: ServerTokenData 암호화 (SessionKey, IV)
note left: TA와 인가앱은 서버토큰 발급 전에 이미 세션키를 교환한 상태이다.
ta --> ca--: 암호화된 ServerTokenData 전달 (IV)
ca -> ca: ServerTokenData 복호화
ca -> ca : ServerToken 생성 (ServerTokenData)
ca -> ta: TA 요청시 ServerToken 제출

@enduml