@startebnf term_ALPHA
ALPHA = ? a-z, A-Z ?;
@endebnf

@startebnf term_BIT
BIT = ? 0, 1 ?;
@endebnf

@startebnf term_DIGIT
DIGIT = ? 0-9 ?;
@endebnf

@startebnf term_HEXDIG
HEXDIG = ? 0-9, a-f, A-F ?;
@endebnf

@startebnf nonterm_identifier
identifier = (ALPHA | "_"), {ALPHA | DIGIT | "_"};
@endebnf

@startebnf nonterm_item_name
item-name = {ALPHA | DIGIT | "_" (* underbar *) | "-" (* dash *) | "." (* dot *)}-;
@endebnf
